### PR TITLE
DATAUP-727: Fix an import spec parse bug re trailing separators

### PR DESCRIPTION
**Pull request by MrCreosote**
If an xSV file is opened and saved by Excel, it'll add trailing separators to
the end of the first header line. This fix ignores those separators.

### CODE REVIEW

**Comment by MrCreosote** [comment]
I don't know what the heck is going on with the tests, they pass locally and the test that is failing is saying an ascii file that the tests write isn't a test file. I'm using the same function to write other files so this is odd.

**Comment by bio-boris** [comment]
I get a failure locally 
```
(staging396) bsadkhin@Boriss-MacBook-Pro ~/m/staging_service (dev-xsvparserbugfix) [1]> python --version                                                                            (base)
Python 3.9.6
```

**Comment by MrCreosote** [comment]
@bio-boris ok, looks fixed

**Comment by bio-boris** [comment]
LGTM

**Pull request merged**
